functions:
  foo:
    path: foo
    handlers:
      get:
        function: functions/foo

  bar:
    path: bar/:id(\d+)
    handlers:
      get:
        function: functions/bar/get
      post:
        function: functions/bar/post
